"""
The HTML report.

Assembles the narrative from `content.json` and the charts and tables from the
model, into one self-contained file. Because the numbers are generated rather
than typed, re-running the model updates every figure in the document at once.
"""
from . import charts as G
from . import config as C
from . import content as content_mod
from . import figures as F
from . import theme as T
from .model import Model




def _table(head, rows, label="") -> str:
    lab = '<div class="tlab">%s</div>' % label if label else ""
    th = "".join("<th>%s</th>" % h for h in head)
    body = ""
    for r in rows:
        cls = ' class="tot"' if str(r[0]).lower().startswith(("total", "all ")) else ""
        body += "<tr%s>%s</tr>" % (cls, "".join("<td>%s</td>" % c for c in r))
    return (lab + '<div class="tw"><table><thead><tr>%s</tr></thead>'
            '<tbody>%s</tbody></table></div>' % (th, body))


def _figure(number, title, caption, svg) -> str:
    out = '<figure><div class="flab">Figure %d</div>' % number
    if title:
        out += '<div class="ttl">%s</div>' % title
    out += svg
    if caption:
        out += "<figcaption>%s</figcaption>" % caption
    return out + "</figure>"


def build(m: Model, blocks=None, path=None) -> str:
    """Assemble the report and return the path written."""
    blocks = blocks if blocks is not None else content_mod.load()
    path = path or (C.OUT / "report.html")

    bands = m.band_summary()
    agencies = m.agency_summary()

    # Figures the narrative already captions keep the written caption; the
    # rest carry the caption the figure generates for itself, which changes
    # with the slicer.
    captioned = {b[1] for b in blocks if b[0] == "figure" and b[3]}
    generated = F.build(m, bands, captioned)

    body, nav = [], []
    for block in blocks:
        kind = block[0]
        if kind == "h2":
            anchor = block[1].lower().replace(" ", "-")[:24]
            nav.append((anchor, block[1]))
            body.append('<h2 id="%s">%s</h2>' % (anchor, block[1]))
        elif kind == "h3":
            anchor = "s" + (block[1] or str(len(nav)))
            nav.append((anchor, "%s · %s" % (block[1], block[2])))
            body.append('<h3 id="%s"><span class="n">%s</span>%s</h3>'
                        % (anchor, block[1], block[2]))
        elif kind == "sub":
            body.append("<h4>%s</h4>" % block[1])
        elif kind == "p":
            body.append("<p>%s</p>" % block[1])
        elif kind == "note":
            body.append('<p class="note">%s</p>' % block[1])
        elif kind == "flag":
            body.append('<p class="flag">%s</p>' % block[1])
        elif kind == "takeaway":
            body.append('<p class="tk"><em>%s</em>%s</p>' % (block[2], block[1]))
        elif kind == "empty":
            body.append('<div class="empty">%s</div>' % block[1])
        elif kind == "list":
            body.append('<ul class="asm">%s</ul>'
                        % "".join("<li>%s</li>" % x for x in block[1]))
        elif kind == "table":
            body.append(_table(block[2], block[3], block[1]))
        elif kind == "figure":
            number, title, caption = block[1], block[2], block[3]
            svg = generated.get(number)
            if svg is None:
                svg = ('<div class="empty">Figure %d is not regenerated by the '
                       "model — see README.</div>" % number)
            body.append(_figure(number, title, caption, svg))

    donors = agencies["donors"].sum()
    stats = [
        (format(int(round(donors)), ",d"), "donors acquired by agencies"),
        ("€%.1fm" % (agencies["cost"].sum() / 1e6), "acquisition spend"),
        ("€%.1fm" % (bands["gross_income"].sum() / 1e6),
         "%d-year gross income" % (C.HORIZON_MONTHS // 12)),
        ("€%.1fm" % (bands["net_income"].sum() / 1e6),
         "%d-year net income" % (C.HORIZON_MONTHS // 12)),
    ]
    stat_html = ('<div class="statlab">Projected</div><div class="stats">'
                 + "".join('<div class="stat"><b>%s</b><span>%s</span></div>' % s
                           for s in stats) + "</div>")
    nav_html = "".join('<a href="#%s">%s</a>' % n for n in nav)

    html = """<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Germany F2F — Optimising Net Income and Net LTV</title>
<style>%s%s</style></head><body>
<header class="top"><div class="inner">
<div class="eyebrow">Germany · Face-to-face agency donors</div>
<h1>Optimising Net Income and Net LTV</h1>
<p>What we ask donors to give, who we ask, and what to do about it.</p>
%s%s</div></header>
<div class="wrap"><nav><div class="lbl">Contents</div>%s</nav><main>%s</main></div>
<footer>%s</footer>
<script>%s</script>
</body></html>""" % (T.css(), G.SLICER_CSS, stat_html, T.logo_html(), nav_html,
                      "\n".join(body), T.footer(), G.SLICER_JS)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")
    return str(path)
